### ISSUE TITLE
polysemy-plugin unable to find polysemy

### ISSUE THREAD

**Issue by Burtannia** [tek/incipit#10]
Hey, I've just started using `incipit` in a project. Unfortunately I get the following error:
```
         `polysemy-plugin` is loaded, but `polysemy` isn't available as a package.
         Probable fix: add `polysemy` to your cabal `build-depends`
 ```
 
Is it necessary to include `polysemy` too or is there a way to get it to rely on the re-export from `incipit`?

**Comment by Burtannia** [comment]
It seems from looking at the source, `incipit` doesn't actually re-export `polysemy` which is how I'd interpreted this line from the readme:
"exporting most of Polysemy's core modules"

**Comment by tek** [comment]
yeah I don't think that's possible 🙂 would be nice though
